In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv('train.csv')
df = df.drop(['Name','Cabin','Ticket','PassengerId','Embarked'], axis=1)
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [33]:
from sklearn.preprocessing import LabelBinarizer, LabelEncoder
sex_encoder = LabelEncoder()
df.Sex = sex_encoder.fit_transform(df.Sex)
sex_encoder.classes_

array(['female', 'male'], dtype=object)

In [32]:
df = df.dropna()

In [28]:
# embark_encoder = LabelBinarizer()
# embark_encoded = embark_encoder.fit_transform(df.Embarked)
# df.Embarked = embark_encoded

In [34]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [38]:
from sklearn.preprocessing import StandardScaler

X = df.iloc[:,1:]
y = df.Survived

X = StandardScaler().fit_transform(X)
X

array([[ 0.91123237,  0.75905134, -0.53037664,  0.52457013, -0.50589515,
        -0.51897787],
       [-1.47636364, -1.31743394,  0.57183099,  0.52457013, -0.50589515,
         0.69189675],
       [ 0.91123237, -1.31743394, -0.25482473, -0.55170307, -0.50589515,
        -0.50621356],
       ..., 
       [-1.47636364, -1.31743394, -0.73704057, -0.55170307, -0.50589515,
        -0.08877362],
       [-1.47636364,  0.75905134, -0.25482473, -0.55170307, -0.50589515,
        -0.08877362],
       [ 0.91123237,  0.75905134,  0.15850313, -0.55170307, -0.50589515,
        -0.50952283]])

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import cross_val_score

lr_clf = LogisticRegression(C=1, random_state=42)
lr_clf.fit(X,y)
print(cross_val_score(lr_clf, X,y, cv=3))

dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(X,y)
print(cross_val_score(dt_clf,X,y,cv=3))

[ 0.79079498  0.78991597  0.79324895]
[ 0.75313808  0.78151261  0.77637131]


In [46]:
test_file = pd.read_csv('test.csv')
test_file.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [61]:
test = test_file.ix[:,['Pclass','Sex','Age','SibSp','Parch','Fare']]
test.head()

Pclass     Sex   Age  SibSp  Parch     Fare
0       3    male  34.5      0      0   7.8292
1       3  female  47.0      1      0   7.0000
2       2    male  62.0      0      0   9.6875
3       3    male  27.0      0      0   8.6625
4       3  female  22.0      1      1  12.2875

In [62]:
test.Sex = sex_encoder.transform(test.Sex)
test.head()

Pclass  Sex   Age  SibSp  Parch     Fare
0       3    1  34.5      0      0   7.8292
1       3    0  47.0      1      0   7.0000
2       2    1  62.0      0      0   9.6875
3       3    1  27.0      0      0   8.6625
4       3    0  22.0      1      1  12.2875

In [67]:
from sklearn.preprocessing import Imputer

imputer = Imputer(strategy='median')
test = imputer.fit_transform(test)

In [69]:
test_scaled = StandardScaler().fit_transform(test)
y_pred = lr_clf.predict(test_scaled)

In [70]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0,

In [91]:
final = test_file
final['Survived'] = y_pred
final = final.ix[:,[0,-1]]
final=final.set_index('PassengerId')
final.head()
final.to_csv('result1.csv')
